---
title             : "COG-ED Manuscript"
author            : "Josephine"
date              : "13 8 2021"
output            : html_document
bibliography      : ref_COG-ED.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bibtex)
```

# Introduction

In everyday life, effort and reward are closely intertwined [@Botvinick2009].
With each decision a person makes, they have to evaluate whether the effort required to reach a goal is worth being exerted, given the reward they receive when reaching the goal.
A reward is subjectively more valuable if it is obtained with less effort, so the required effort is used as a reference point for estimating the reward value [@Botvinick2009].
However, the cost of the effort itself is also subjective, and research has not yet established which function best describes the relationship between effort and cost [@Kool2018].
Investigating effort and cost is challenging because “effort is not a property of the target task alone, but also a function of the individual’s cognitive capacities, as well as the degree of effort voluntarily mobilized for the task, which in turn is a function of the individual’s reward sensitivity” [@Kool2018, p. 209].

One task that is often used to investigate effort is the n-back task, a working memory task in which a continuous stream of stimuli, e.g. letters, is presented on screen and participants indicate via button press whether the current stimulus is the same as *n* stimuli before, with *n* being the level of difficulty between one and six [@Mackworth1959].
It requires simultaneous storage of past stimuli and processing of new stimuli [@Jonides1997], and participants are asked to respond as quickly and as accurately as they can.
The n-back task is well suited to investigate effort because it is an almost continuous manipulation of task load, as has been shown by monotonic increases in error rates and reaction times [@Jaeggi2010] as well as monotonic increases in brain activity in areas associated with working memory [@Jonides1997; @Owen2005].
However, reliability measures of the n-back task are mixed, presumably due to ceiling effects in performance in the easiest level, causing inconsistent associations of n-back performance and measures such as executive functioning and fluid intelligence [@Jaeggi2010].

A way to quantify the subjective cost of each n-back level has been developed by Westbrook et al. [-@Westbrook2013], called the Cognitive Effort Discounting Paradigm (COG-ED).
First, the participants complete n-back level one to six to familiarize themselves with the task.
Then, each level two to six is being compared with level one by asking the participants to decide between receiving 2\$ for the more difficult level or 1\$ for level one.
It they choose the more difficult level, the reward for level one increases by 0.50\$, if the choose level one, it decreases by 0.50\$.
This is repeated five more times, with each adjustment of the level one reward being half as big as in the previous step, while the reward for the more difficult level remains fixed at 2\$.
The idea is to estimate the participants' subjective cost of the more difficult level by identifying the smallest reward they would still be okay with being paid for doing level one.
Therefore, the higher the difficult level, the smaller the reward that the participants would accept for level one.
The subjective value (SV) of each difficult level is then calculated by dividing the final reward value of level one by the fixed 2\$ reward of the difficult level.
Westbrook et al. [-@Westbrook2013] used these SVs to investigate interindividual differences in effort discounting by plotting the SVs and computing an area under the curve (AUC).
Younger participants had a larger AUC than older participants, i.e. they needed a lower monetary incentive for choosing the more difficult levels over level one.

The AUC in the study by Westbrook et al. [-@Westbrook2013] was also associated with the participants' Need for Cognition score, a personality trait describing individuals who actively seek and enjoy effortful cognitive activities [@Cacioppo1982].



-	higher n-back levels and more difficult signal-to-noise audio comprehension task levels are discounted in similar ways in the COG-ED paradigm -> doesn’t just work for n-back (Crawford et al., 2021)
-	there are strong within-subjects associations of the SV of different cognitive domains, i.e. n-back and audio comprehension, even after controlling for performance d’, and even though the audio task was rated as less mentally demanding and effortful (Crawford et al., 2021)

-	n-back performance is not associated with NFC (and neither are a battery of other tasks of executive functioning) -> NFC reflects a motivation, not ability (Gärtner et al., 2021)
-	however, NFC is associated with brain flexibility on multiple levels (He et al., 2019)
-	NFC correlates with greater automatic attention allocation (measured in ERPs) in easier tasks and also with greater voluntary attention allocation in more difficult tasks (Enge et al., 2008)
-	NFC is positively related to gf and gc but not working memory (Hill et al., 2013)
-	NFC is not associated with memory and gf, and anecdotally with gc (Fleischhauer et al., 2010)
-	performance, indexed by d’, was not a reliable predictor of SV across SCZ patients and healthy controls (Culbreth et al., 2016)
-	when adding the performance scores d’ as a mean performance score as a covariate, the effects of NFC on SV disappeared -> willingness to invest effort might have partially been driven by the prospect of success (Kramer et al., 2021)
-	in a multilevel model, task load was associated with SVs beyond performance d’ (Westbrook et al., 2013)
-	older adults make the SV decisions more with their performance in mind than young adults (McLaughlin et al., 2021)

-	higher NFC means higher motivation to voluntarily mobilize effort for the task, because it is perceived as intrinsically rewarding
-	the SV of n=1 vs n=2 correlates positively with NFC in children, but not of n=1 vs n=3 (Chevalier, 2018)
-	the SV of n=1 vs n=3 correlates positively with NFC in adolescents, but not of n=1 vs n=2
(Kramer et al., 2021)
-	no association of SV and NFC in either n-back or audio comprehension in a sample of 31 adults (Crawford et al., 2021)
Justifying changes in the COG-ED procedure:
-	subjective values did not decline between n=4 and n=5 (Culbreth et al., 2016) -> n=5 is too universally difficult to be valid
-	only higher n-back levels are reliable for performance computation (Jaeggi et al., 2010) -> we will not include n = 1 in our performance measure

